services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  pma:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    depends_on: 
      - db
    ports:
      - 6080:80
    profiles:
      - debug
    restart: always

  technest:
    build: ./
    depends_on:
      - "db"
    ports: 
      - 8080:80

 #   volumes:
 #     - .\:/var/www/html
 #     - .\storage\app\public:/var/www/html/public/storage
